#!/bin/bash

maxfile="/sys/class/backlight/intel_backlight/max_brightness"
file="/sys/class/backlight/intel_backlight/brightness"
NOTIFY_ID_FILE="/tmp/brightness-notify"

maxvalue=$(cat "$maxfile")
value=$(cat "$file")
minvalue=0

if [ -z "$1" ] ; then
    echo "Current Value: "$value
    echo "Percentage: "$(($value*100/$maxvalue))"%"
    exit
fi

if [ $1 == '%' ] ; then
    echo $(($value*100/$maxvalue))"%"
    exit
fi

var1=$1
if [ $1 == '+' ] || [ $1 == '-' ] ; then
    var1=-50
    if [ $1 == '+' ]; then
        var1=50
    fi
    if [ $value -gt 9 ]; then
        var1=$(($var1 + $value))
    fi
fi

if (( $var1 > $maxvalue )) || (( $var1 < $minvalue )) ; then
        echo "Error : Out of range"
        echo "Max is: " $maxvalue
        echo "Min is: " $minvalue
        echo "Current Brightness: " $value
        diff=$(($var1-$value))
        echo "Incremental/Decremental Value: "$diff 
        echo "Given Value: "$var1
        if (( $var1 > $maxvalue )) ; then
            var1=$maxvalue
        fi
        if (( $var1 < $minvalue )) ; then
            var1=$minvalue
        fi
        echo "Set Value: " $var1
        echo
        echo $var1 | sudo tee $file
        exit
fi
    echo $var1
    echo $var1 | sudo tee $file
    NOTIFY_ID=$(cat $NOTIFY_ID_FILE)
    PERCENTAGE=$(($value*100/$maxvalue))"%"
    dunstify -p -r ${NOTIFY_ID:=0} -u low -a volume -i sunny Brightness $PERCENTAGE > $NOTIFY_ID_FILE
