#!/bin/bash

maxfile="/sys/class/backlight/radeon_bl0/max_brightness"
file="/sys/class/backlight/radeon_bl0/brightness"

maxvalue=$(cat "$maxfile")
value=$(cat "$file")
minvalue=0

if [ -z "$1" ] ; then
    echo "Current Value: "$value
    echo "Percentage: "$(($value*100/$maxvalue))"%"
    exit
fi

if [ $1 == '%' ] ; then
    echo $(($value*100/$maxvalue))"%"
    exit
fi

var1=$1
if [ $1 == '+' ] || [ $1 == '-' ] ; then
    var1=-10
    if [ $1 == '+' ]; then
        var1=10
    fi
    if [ $value -gt 9 ]; then
        var1=$(($var1 + $value)) 
    fi
fi

if (( $var1 > $maxvalue )) || (( $var1 < $minvalue )) ; then
        echo "Error : Out of range"
        echo "Max is: " $maxvalue
        echo "Min is: " $minvalue
        echo "Current Brightness: " $value
        diff=$(($var1-$value))
        echo "Incremental/Decremental Value: "$diff 
        echo "Given Value: "$var1
        if (( $var1 > $maxvalue )) ; then
            var1=$maxvalue
        fi
        if (( $var1 < $minvalue )) ; then
            var1=$minvalue
        fi
        echo "Set Value: " $var1
        echo $var1 > "$file"
        exit
fi
    echo $var1
    echo $var1 > "$file"
