#!/usr/bin/env python3
import os


HOME = os.getenv("HOME")
VENVDIR = os.path.join(HOME, ".venv")  # <-- Change this to your venv dir.
VENVFILENAME = ".venv"


def main():
    """
    use as $(envactive) to active virtualenv
    project folder name and .venv/{virtulenv} is same
    i.e deep -> ~/.venv/deep/bin/activate
    """
    path = os.getcwd().split(os.sep)

    while(path):
        if(os.path.isdir(os.path.join(os.sep, *path, '.git'))):
            print('source {}'.format(
                os.path.join(VENVDIR,
                             path.pop(),
                             'bin', 'activate')))
            break
        path.pop()


if __name__ == '__main__':
    main()
