#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;
my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;

# read the first line of the "acpi" command output
open (ACPI, 'acpi -b |') or die "Can't exec acpi: $!\n";
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

my $filename = '.batteryStatus';
unless(-e $filename) {
    #Create the file if it doesn't exist
    open (Fc, ">$filename") or die "cant open file\n";
    print Fc $status ;
    close(Fc);
    print("hello");
}

open (Status, "+<",$filename) or die "cant open file\n";
my $prevStatus = <Status>;
close(Status);
open (Status, ">",$filename) or die "cant open file\n";
print Status $status ; 
close(Status);

if ( $status ne $prevStatus ){
    if ( $status eq 'Charging'){
        system("notify-send -i battery-caution-charging Battery \"Plugged\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg");
    }elsif( $status eq 'Discharging'){
        system("notify-send -i battery Battery \"UnPlugged\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg");
    }else{
        system("notify-send -i battery-full-charged Battery \"Battery Full\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg");
    }
}

if ($status eq 'Discharging') {
	
} elsif ($status eq 'Charging') {
	$full_text .= ' ';
}else{
	$full_text .= ' ';
}

if ($percent < 5) {
		$full_text .= '';
    }elsif ($percent < 15) {
        if ( $status eq 'Discharging'){
        system("notify-send -i battery-low Battery \"Battery Low\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg ");
        }
    }elsif ($percent < 20) {
		$full_text .= ' ';
	}elsif ($percent < 40) {
		$full_text .= ' ';
    }elsif ($percent < 60) {
		$full_text .= ' ';
	}elsif ($percent < 90) {
		$full_text .= " ";
    }else{ 
        $full_text .= ' ';
    }

if ($percent < 100) { 
$full_text .= "$percent%";
}
$short_text .= $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";


# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {
    if($percent < 15) {
        print "#FF0000\n";
    }elsif ($percent < 20) {
		print "#FF4400\n";
	} elsif ($percent < 40) {
		print "#FFAE00\n";
	} elsif ($percent < 60) {
		print "#FFF600\n";
	} elsif ($percent < 85) {
		print "#A8FF00\n";
	} elsif($percent < 101){
        print "\#00FF00";
    }
}else{
    print "#00FF00\n";
}

exit(0);
