#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;
my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;

# read the first line of the "acpi" command output
open (ACPI, 'acpi -b |') or die "Can't exec acpi: $!\n";
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

my $filename = '/tmp/.batteryStatus';
unless(-e $filename) {
    #Create the file if it doesn't exist
    open (Fc, ">$filename") or die "cant open file\n";
    print Fc $status ;
    close(Fc);
    print(" ");
}

open (Status, "+<",$filename) or die "cant open file\n";
my $prevStatus = <Status>;
close(Status);
open (Status, ">",$filename) or die "cant open file\n";
print Status $status ;
close(Status);

if ( $status ne $prevStatus ){
    if ( $status eq 'Charging'){
        system("notify-send -i battery-good-charging Battery \"Plugged\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg");
    }elsif( $status eq 'Discharging'){
        system("notify-send -i battery-medium Battery \"UnPlugged\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg");
    }else{
        system("notify-send -i battery-full-charging Battery \"Battery Full\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg");
    }
}

if ($status eq 'Discharging') {
	
} elsif ($status eq 'Charging') {
	$full_text .= ' ';
}else{
	$full_text .= ' ';
}

if ($percent < 20) {
    if ($percent < 20){$full_text .= ' ';}
    if ($percent < 10){$full_text .= ' ';}
    if ( $status eq 'Discharging' && $percent < 15){
        my $diffTime = 5*60;
        my $filenameTime = '/tmp/.batteryTime';
        my $time = `date +%s`;
        unless(-e $filenameTime) {
            #Create the file if it doesn't exist
            open (Fc, ">$filenameTime") or die "cant open file\n";
            print Fc $time ;
            close(Fc);
        }
        open (Time, "+<",$filenameTime) or die "cant open file\n";
        my $prevTime = <Time>;
        close(Status);
        if ($time - $prevTime > $diffTime) {
            system("notify-send -u critical -i battery-caution Battery \"Battery Low\" && paplay /usr/share/sounds/ubuntu/stereo/system-ready.ogg ");
            open (Time, ">",$filenameTime) or die "cant open file\n";
            print Time $time ;
            close(Time);
        }
    }
}elsif ($percent < 40) {
    $full_text .= ' ';
}elsif ($percent < 60) {
    $full_text .= ' ';
}elsif ($percent < 90) {
    $full_text .= " ";
}else{ 
    $full_text .= ' ';
}

if ($percent < 100) { 
$full_text .= "$percent%";
}
$short_text .= $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";


# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {
    if($percent < 15) {
        print "#c54040\n";
    }elsif ($percent < 20) {
		print "#f59696\n";
	} elsif ($percent < 40) {
		print "#c59696\n";
	} elsif ($percent < 60) {
		print "#959696\n";
	} elsif ($percent < 85) {
		print "#659696\n";
	} elsif($percent < 101){
        print "#359696\n";
    }
}else{
    print "#32d8b3\n";
}

exit(0);
