#!/bin/bash

$HOME/git/myconfig/script/volume.py read

if  [ "${BLOCK_BUTTON}" == "1" ] || [ "${BLOCK_BUTTON}" == "3" ]; then
    $HOME/git/myconfig/script/volume.py toggle
elif [ "${BLOCK_BUTTON}" == "4" ]; then
    $HOME/git/myconfig/script/volume.py up 10
elif [ "${BLOCK_BUTTON}" == "5" ]; then
    $HOME/git/myconfig/script/volume.py down 10
fi
