#!/bin/bash

case $BLOCK_BUTTON in
    [1-2]) $HOME/git/myconfig/script/volume.py toggle >> /dev/null;;   # toggle mute
    4) $HOME/git/myconfig/script/volume.py up 10 ;;  # volume up
    5) $HOME/git/myconfig/script/volume.py down 10 ;;  # volume down
esac

$HOME/git/myconfig/script/volume.py read
